[profile.release]
panic = 'unwind'

[workspace]
members = [
	'kitchen-node',
	'pallets/*',
	'super-runtime',
]

[patch.crates-io]
# sc-service = { path = "./client/service"}
sc-block-builder = { path = "./client/block-builder"}
sc-basic-authorship = { path = "./client/basic-authorship"}